### ISSUE TITLE
"URL encoding" is actually the Base64 URL variant

### ISSUE THREAD

**Issue by OrangeDog** [burzek/StringFunctionsPlugin#1]
I expected it to be actual URL encoding (i.e. percent-encoding).

**Comment by burzek** [comment]
Hm...you're right, thanks for feedback, i'll fix it asap.

**Comment by OrangeDog** [comment]
Can you also make sure it's the proper RFC 3986 version.
Lots of tools still convert space to `+`, which is very annoying.

**Comment by burzek** [comment]
fixed, plugin version 4.0 is waiting to be approved by intellij

**Comment by burzek** [comment]
marked as fixed
